---
title: CSC233 HW 01
---


# CSC 233: Assignment 1, Due Jan 20, 2026, before class


## 1. Setup Colab Notebook (1 pts)

1. Make a copy of the Colab Notebook template: 

<https://drive.google.com/file/d/1_FH32gu7P_SzzLX7yeNejaxZ9s5cpCid/view?usp=sharing>

2. Rename it with your own name: [Name]_CSC233_W26_Assignment1.ipynb

3. Follow the instructions in the Colab Notebook.

assignment1.csv: <https://drive.google.com/file/d/1FMtPBR3YvZaONBNrk-87qoTFhlIT4j1x/view?usp=sharing>

4. Share your notebook with me (doingg@union.edu) as your submission.

## 2. Project Proposal (1 pts)

1.  Make a copy of the Project Proposal Notebook template: <https://colab.research.google.com/drive/1jSCGEu13RRWJyG-cMt5KmSWa2lVmhVgv?usp=sharing> 

2. Explore **3** data sets from 3 different data sources you might use

* record your data sets/sources, justifications and interest in Markdown cells
* be sure to include relevent links
* include considerations as to the quality and trustworthiness of your sources
* note that it is OK if your final project does not end up using these exact data sets, but you will at least have these as options

## 3. Update Check-in Notebook (1 pts)

1. Review your check-in notebook and scores for last week's homework assignment

2. Include a Markdown chunk that attests to my notes or requests a correction/update

