---
title: CSC233 HW 05
---


# CSC 233: Assignment 5, Due Feb 17 2026, by 10 am


## 1. Colab Notebook (4 pts)

1. Make a copy of the Colab Notebook template: 

<https://drive.google.com/file/d/1pYELYivLOqwg12Z8AaGFsfF6N9QVbmof/view?usp=sharing>

2. Rename it with your own name: [Name]_CSC233_W26_Assignment5.ipynb

3. Follow the instructions in the Colab Notebook. Be sure to comment your code and add Markdown cells to document your work.

4. Share your notebook with me (doingg@union.edu) as your submission.

## 2. Project Outline (1 pts)

1.  In your Colab notebook from last week, with your revised question, outline how you will answer it. Include any more questions that come up as your work through your thought process, any addtional data you may need to search for.

## 3. Runsestone Reading & Activities (2 pts)

1. Read and complete the activities for chapter 6.

Note that there may be some sub-sections that are old review, feel free to skip them. Also feel free to skip any activities that don't seem helpful for this class. You are graded on accessing the pages and attempting activities but do not need to engage with every element for your activity to be clear.






