---
title: CSC 106 Can Computers Think?, Week 7 Practice Problems
date: May, 11th, 2026
eval: true
format: 
    pdf:
        number-sections: false
        shift-heading-level-by: 2
        geometry:
            - top=1in
            - right=.8in
            - bottom=1in
            - left=.8in
        mainfont: "Avenir"
        sansfont: "Avenir"
        code-line-numbers: true
        include-in-header: 
            - ../preamble2.tex
---

NAME:  


# Practice Problems for Week 7

Please complete, bring to class (written answers) and submit on gradescope (code) by end of day on **Monday 5/18/26**.


You will be submitting the following files:  

- list_sums.py

# Programming Part 1: List Sums

In a python file called `list_sums.py`:

Create a 2D list to store the following values:

```
[[5,6,7],
 [1,2,3],
 [8,9,10]]
 ```

Write a function called `sub_list_sums` that returns a list of sums of the sub-list. 
For the above example:
```
5+ 6 + 7 = 18
1+ 2 + 3 = 6
8 + 9 + 10 = 27
```
Returned list should be: `[18,6,27]`

Now write a second function called `column_sums` that returns the sum of the columns:

```
5 + 1 + 8 = 14
6 + 2 + 9 = 17
8 + 9 + 10 = 27
```
Returned list should be: `[14,17,27]`

After defining your functions, add the following line to your code:

`### DO NOT DELETE THIS LINE: beg testing`

Then demonstrate your code working by calling your functions with example data in the same python file.




# Written Questions

Consider the following function definition when answering questions 1-4:
```
def bad_name(number_list):
	if number_list == []:
		return True
	else:
		bad_name_2 = number_list[0]
		for num in number_list:
			if bad_name_2 > num:
				return False
			bad_name_2 = num
		return True
```

1.	What will be the return values when the function above is called as follows?

`bad_name([123,345,474,678])` ………………………………………………………

`bad_name([7,7,7])` ……………………………………………………………

`bad_name([123,345,567,474,678])` …………………………………………………………

`bad_name([4,2,4,8])` ……………………………………………

`bad_name([])` ……………………………………………………………

2.	In general words, what seems to be the purpose of this function?

………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………


3.	Suggest better names for the less than fantastic function and variable names used in this definition.

`bad_name`     ………………………………………………………………………………………………

`bad_name_2`   ………………………………………………………………………………………………




4.	Why is the first if-statement necessary? What would happen if the function definition looked as follows (missing the first if-statement)?
```
def bad_name(number_list):
		bad_name_2 = number_list[0]
		for num in number_list:
			if bad_name_2 > num:
				return False
			bad_name_2 = num
		return True
```


Consider the following list when answering the questions:
```
lists_of_scores = [[3, 12, 6, 8, 23, 5],
			  [18, 12, 9, 10, 6, 20, 15, 17],
			  [8, 12, 11, 7, 9, 9, 16],
			  [4, 9, 10, 3, 6],
			  [20, 21, 18, 16, 12, 19, 23]]
```

What will the following snippets of code print to the screen? If they lead to an error, explain why.

1.	`print(lists_of_scores[2][1])`

………………………………………………………………………………………………

2.	`print(len(lists_of_scores))`

………………………………………………………………………………………………

3.	`print(len(lists_of_scores[1]))`

………………………………………………………………………………………………

4.	`print(len(lists_of_scores[-1][0]))`

………………………………………………………………………………………………


5.	```
for element in lists_of_scores:
     if len(element) < 7:
          print(element)
```


………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………




6.	```
for i in range(0, len(lists_of_scores)):
     for s in lists_of_scores[i]:
          if s > 20:
               print(i)
```


………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………




………………………………………………………………………………………………

………………………………………………………………………………………………

………………………………………………………………………………………………

